version: "3.9"
   
services:
  kiwify-backend:
    container_name: kiwify-backend
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./env/dev/global.env
      - ./env/dev/django.env
